name: AI PR Review Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Triggers for when a PR is opened, updated, or reopened

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checkout your code

      - name: Set up Python (for ChatGPT)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Python version

      - name: Install Dependencies
        run: |
          pip install -r .github/chat-gpt-pr-reviewer/requirements.txt  # Install dependencies from the PR reviewer repo

      - name: Run PR Review Script
        run: |
          python .github/chat-gpt-pr-reviewer/github_reviewer.py  # Make sure this points to the correct file for reviewing
