name: AI PR Review Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Make sure the key is referenced correctly
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r .github/chat-gpt-pr-reviewer/requirements.txt

      - name: Run PR Review Script
        run: |
          python .github/chat-gpt-pr-reviewer/github_reviewer.py
