name: PR Review with ChatGPT

on:
  pull_request:
    types: [opened, synchronize, reopened]  # Triggers when PR is opened, updated, or reopened

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PR review with ChatGPT
        run: |
          python pr_reviewer.py  # Run the Python script that sends PR diffs to ChatGPT

#yash
